apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: infra-tools-test-cicd-app-source
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://github.com/SabinGhost19/infra-tools
  ref:
    branch: main
  timeout: 30s
  ignore: |
    /*
    !/apps/
    /apps/*
    !/apps/test-cicd-app/
    !/apps/test-cicd-app/**
