apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - platform/platform-sources
  - platform/platform-networking
  - platform/platform-mesh
  - platform/platform-observability
  - platform/platform-secrets
  - operators/operator-terraform
  - platform/platform-identity
  - platform/platform-security
  - platform/platform-ci-cd-zero-trust
  - development/dev-apps
